In [36]:
import pandas as pd
import numpy as np

df_treinamento = pd.read_csv('../arquivos_csv/treinamento2.csv', low_memory=False)
df_teste = pd.read_csv('../arquivos_csv/teste2.csv', low_memory=False)

### Remover underscore

In [37]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 
    'Total_EMI_per_month', 'Amount_invested_monthly', 
    'Monthly_Balance'
]

for atributo in atributos:
    df_treinamento[atributo] = df_treinamento[atributo].astype(str).str.replace('_', '', regex=False)
    df_treinamento[atributo] = pd.to_numeric(df_treinamento[atributo], errors='coerce')

In [38]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 
    'Total_EMI_per_month', 'Amount_invested_monthly', 
    'Monthly_Balance'
]

for atributo in atributos:
    df_teste[atributo] = df_teste[atributo].astype(str).str.replace('_', '', regex=False)
    df_teste[atributo] = pd.to_numeric(df_teste[atributo], errors='coerce')

#### Valores unicos para atributos

In [39]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Outstanding_Debt':
[ 809.98  605.03 1303.01 ...  620.64 3571.7   502.38]


Valores únicos no atributo 'Credit_Utilization_Ratio':
[26.82261962 31.94496006 28.60935202 ... 41.25552226 33.63820798
 34.19246265]


Valores únicos no atributo 'Credit_History_Age':
[22. nan 26. 27. 17. 18. 30. 31. 32. 14. 15. 21. 19. 25.  8.  9. 16. 29.
  6.  7. 10. 33. 12. 13. 28. 24.  1. 11. 20.  0.  5.  2.  3. 23.  4.]


Valores únicos no atributo 'Payment_of_Min_Amount':
['No' nan 'Yes']


Valores únicos no atributo 'Total_EMI_per_month':
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]


Valores únicos no atributo 'Amount_invested_monthly':
[ 80.41529544 118.28022162  81

#### Credit_Mix: valores com _ receberam valor nulo

In [40]:
df_treinamento['Credit_Mix'] = df_treinamento['Credit_Mix'].replace('_', np.nan)


In [41]:
df_teste['Credit_Mix'] = df_teste['Credit_Mix'].replace('_', np.nan)


In [42]:
# import matplotlib.pyplot as plt

# # Convertendo 'Outstanding_Debt' para numérico e removendo valores nulos
# df_treinamento['Outstanding_Debt'] = pd.to_numeric(df_treinamento['Outstanding_Debt'], errors='coerce')
# outstanding_debt_clean = df_treinamento['Outstanding_Debt'].dropna()

# # Criando o histograma para visualizar a distribuição
# plt.figure(figsize=(10, 6))
# plt.hist(outstanding_debt_clean, bins=30, edgecolor='black', alpha=0.7)
# plt.title('Distribuição de Outstanding Debt')
# plt.xlabel('Total da Dívida (Outstanding Debt)')
# plt.ylabel('Frequência')
# plt.grid(True)

# # Exibindo o gráfico
# plt.show()

In [43]:
# bins = [0, 1000, 2000, 3000, df_treinamento['Outstanding_Debt'].max()]
# labels = ['Grupo 1: 0-1000', 'Grupo 2: 1000-2000', 'Grupo 3: 2000-3000', 'Grupo 4: >3000']

# df_treinamento['grupo_debito'] = pd.cut(df_treinamento['Outstanding_Debt'], bins=bins, labels=labels, include_lowest=True)


# valores_unicos_grupo_debito = df_treinamento['grupo_debito'].unique()
# print(valores_unicos_grupo_debito)


In [44]:
# bins = [0, 1000, 2000, 3000, df_teste['Outstanding_Debt'].max()]
# labels = ['Grupo 1: 0-1000', 'Grupo 2: 1000-2000', 'Grupo 3: 2000-3000', 'Grupo 4: >3000']

# df_teste['grupo_debito'] = pd.cut(df_teste['Outstanding_Debt'], bins=bins, labels=labels, include_lowest=True)


# valores_unicos_grupo_debito = df_teste['grupo_debito'].unique()
# print(valores_unicos_grupo_debito)


In [45]:
# df_treinamento = df_treinamento.drop(columns=['Outstanding_Debt'])
# df_teste = df_teste.drop(columns=['Outstanding_Debt'])


In [46]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
[22. nan 26. 27. 17. 18. 30. 31. 32. 14. 15. 21. 19. 25.  8.  9. 16. 29.
  6.  7. 10. 33. 12. 13. 28. 24.  1. 11. 20.  0.  5.  2.  3. 23.  4.]


Valores únicos no atributo 'Payment_of_Min_Amount':
['No' nan 'Yes']


Valores únicos no atributo 'Total_EMI_per_month':
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]


Valores únicos no atributo 'Amount_invested_monthly':
[ 80.41529544 118.28022162  81.69952126 ...  24.02847745 251.6725822
 167.16386516]


Valores únicos no atributo 'Payment_Behaviour':
['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'

In [47]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_teste[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
[22. nan 26. 27. 17. 18. 30. 31. 32. 14. 15. 21. 19. 25.  8.  9. 16. 29.
  6.  7. 10. 33. 12. 13. 28. 24.  1. 11. 20.  0.  5.  2.  3. 23.  4.]


Valores únicos no atributo 'Payment_of_Min_Amount':
['No' nan 'Yes']


Valores únicos no atributo 'Total_EMI_per_month':
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]


Valores únicos no atributo 'Amount_invested_monthly':
[ 80.41529544 118.28022162  81.69952126 ...  24.02847745 251.6725822
 167.16386516]


Valores únicos no atributo 'Payment_Behaviour':
['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'

In [48]:
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].str[:2]
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].str.replace(' ', '')

df_treinamento['Credit_History_Age'] = pd.to_numeric(df_treinamento['Credit_History_Age'], errors='coerce')
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].astype('Int64')

AttributeError: Can only use .str accessor with string values!

In [ ]:
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].str[:2]
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].str.replace(' ', '')

df_teste['Credit_History_Age'] = pd.to_numeric(df_teste['Credit_History_Age'], errors='coerce')
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].astype('Int64')

#### Payment_of_Min_Amount

In [ ]:
df_treinamento['Payment_of_Min_Amount'] = df_treinamento['Payment_of_Min_Amount'].replace('NM', np.nan)

In [ ]:
df_teste['Payment_of_Min_Amount'] = df_teste['Payment_of_Min_Amount'].replace('NM', np.nan)

### Salvando Dados

In [ ]:
df_treinamento.to_csv('../arquivos_csv/treinamento2.csv', index=False)
df_teste.to_csv('../arquivos_csv/teste2.csv', index=False)
