In [1]:
import pandas as pd
import numpy as np

df_treinamento = pd.read_csv('../arquivos_csv/treinamento2.csv', low_memory=False)
df_teste = pd.read_csv('../arquivos_csv/teste2.csv', low_memory=False)

### Remover underscore

In [2]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 
    'Total_EMI_per_month', 'Amount_invested_monthly', 
    'Monthly_Balance'
]

for atributo in atributos:
    df_treinamento[atributo] = df_treinamento[atributo].astype(str).str.replace('_', '', regex=False)
    df_treinamento[atributo] = pd.to_numeric(df_treinamento[atributo], errors='coerce')

In [3]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 
    'Total_EMI_per_month', 'Amount_invested_monthly', 
    'Monthly_Balance'
]

for atributo in atributos:
    df_teste[atributo] = df_teste[atributo].astype(str).str.replace('_', '', regex=False)
    df_teste[atributo] = pd.to_numeric(df_teste[atributo], errors='coerce')

#### Valores unicos para atributos

In [4]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Outstanding_Debt', 'Credit_Utilization_Ratio', 'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
['_' 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Outstanding_Debt':
[ 809.98  605.03 1303.01 ...  620.64 3571.7   502.38]


Valores únicos no atributo 'Credit_Utilization_Ratio':
[26.82261962 31.94496006 28.60935202 ... 41.25552226 33.63820798
 34.19246265]


Valores únicos no atributo 'Credit_History_Age':
['22 Years and 1 Months' nan '22 Years and 3 Months'
 '22 Years and 4 Months' '22 Years and 5 Months' '22 Years and 6 Months'
 '22 Years and 7 Months' '26 Years and 7 Months' '26 Years and 8 Months'
 '26 Years and 9 Months' '26 Years and 10 Months' '26 Years and 11 Months'
 '27 Years and 0 Months' '27 Years and 1 Months' '27 Years and 2 Months'
 '17 Years and 9 Months' '17 Years and 10 Months' '17 Years and 11 Months'
 '18 Years and 1 Months' '1

#### Credit_Mix: valores com _ receberam valor nulo

In [5]:
df_treinamento['Credit_Mix'] = df_treinamento['Credit_Mix'].replace('_', np.nan)


In [6]:
df_teste['Credit_Mix'] = df_teste['Credit_Mix'].replace('_', np.nan)


In [7]:
# import matplotlib.pyplot as plt

# # Convertendo 'Outstanding_Debt' para numérico e removendo valores nulos
# df_treinamento['Outstanding_Debt'] = pd.to_numeric(df_treinamento['Outstanding_Debt'], errors='coerce')
# outstanding_debt_clean = df_treinamento['Outstanding_Debt'].dropna()

# # Criando o histograma para visualizar a distribuição
# plt.figure(figsize=(10, 6))
# plt.hist(outstanding_debt_clean, bins=30, edgecolor='black', alpha=0.7)
# plt.title('Distribuição de Outstanding Debt')
# plt.xlabel('Total da Dívida (Outstanding Debt)')
# plt.ylabel('Frequência')
# plt.grid(True)

# # Exibindo o gráfico
# plt.show()

In [8]:
# bins = [0, 1000, 2000, 3000, df_treinamento['Outstanding_Debt'].max()]
# labels = ['Grupo 1: 0-1000', 'Grupo 2: 1000-2000', 'Grupo 3: 2000-3000', 'Grupo 4: >3000']

# df_treinamento['grupo_debito'] = pd.cut(df_treinamento['Outstanding_Debt'], bins=bins, labels=labels, include_lowest=True)


# valores_unicos_grupo_debito = df_treinamento['grupo_debito'].unique()
# print(valores_unicos_grupo_debito)


In [9]:
# bins = [0, 1000, 2000, 3000, df_teste['Outstanding_Debt'].max()]
# labels = ['Grupo 1: 0-1000', 'Grupo 2: 1000-2000', 'Grupo 3: 2000-3000', 'Grupo 4: >3000']

# df_teste['grupo_debito'] = pd.cut(df_teste['Outstanding_Debt'], bins=bins, labels=labels, include_lowest=True)


# valores_unicos_grupo_debito = df_teste['grupo_debito'].unique()
# print(valores_unicos_grupo_debito)


In [10]:
# df_treinamento = df_treinamento.drop(columns=['Outstanding_Debt'])
# df_teste = df_teste.drop(columns=['Outstanding_Debt'])


In [11]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
['22 Years and 1 Months' nan '22 Years and 3 Months'
 '22 Years and 4 Months' '22 Years and 5 Months' '22 Years and 6 Months'
 '22 Years and 7 Months' '26 Years and 7 Months' '26 Years and 8 Months'
 '26 Years and 9 Months' '26 Years and 10 Months' '26 Years and 11 Months'
 '27 Years and 0 Months' '27 Years and 1 Months' '27 Years and 2 Months'
 '17 Years and 9 Months' '17 Years and 10 Months' '17 Years and 11 Months'
 '18 Years and 1 Months' '18 Years and 2 Months' '18 Years and 3 Months'
 '18 Years and 4 Months' '17 Years and 3 Months' '17 Years and 4 Months'
 '17 Years and 5 Months' '17 Years and 6 Months' '17 Years and 7 Months'
 '17 Years and 8 Months' '30 Years and 8 Months

In [12]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_teste[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
['22 Years and 1 Months' nan '22 Years and 3 Months'
 '22 Years and 4 Months' '22 Years and 5 Months' '22 Years and 6 Months'
 '22 Years and 7 Months' '26 Years and 7 Months' '26 Years and 8 Months'
 '26 Years and 9 Months' '26 Years and 10 Months' '26 Years and 11 Months'
 '27 Years and 0 Months' '27 Years and 1 Months' '27 Years and 2 Months'
 '17 Years and 9 Months' '17 Years and 10 Months' '17 Years and 11 Months'
 '18 Years and 1 Months' '18 Years and 2 Months' '18 Years and 3 Months'
 '18 Years and 4 Months' '17 Years and 3 Months' '17 Years and 4 Months'
 '17 Years and 5 Months' '17 Years and 6 Months' '17 Years and 7 Months'
 '17 Years and 8 Months' '30 Years and 8 Months

In [13]:
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].str[:2]
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].str.replace(' ', '')

df_treinamento['Credit_History_Age'] = pd.to_numeric(df_treinamento['Credit_History_Age'], errors='coerce')
df_treinamento['Credit_History_Age'] = df_treinamento['Credit_History_Age'].astype('Int64')

In [14]:
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].str[:2]
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].str.replace(' ', '')

df_teste['Credit_History_Age'] = pd.to_numeric(df_teste['Credit_History_Age'], errors='coerce')
df_teste['Credit_History_Age'] = df_teste['Credit_History_Age'].astype('Int64')

#### Payment_of_Min_Amount

In [15]:
df_treinamento['Payment_of_Min_Amount'] = df_treinamento['Payment_of_Min_Amount'].replace('NM', np.nan)

In [16]:
df_teste['Payment_of_Min_Amount'] = df_teste['Payment_of_Min_Amount'].replace('NM', np.nan)

### Salvando Dados

In [17]:
df_treinamento.to_csv('../arquivos_csv/treinamento2.csv', index=False)
df_teste.to_csv('../arquivos_csv/teste2.csv', index=False)
