In [1]:
import pandas as pd
import numpy as np

df_treinamento = pd.read_csv('../arquivos_csv/treinamento2.csv', low_memory=False)
df_teste = pd.read_csv('../arquivos_csv/teste2.csv', low_memory=False)


In [2]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")


Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
[22. nan 26. 27. 17. 18. 30. 31. 32. 14. 15. 21. 19. 25.  8.  9. 16. 29.
  6.  7. 10. 33. 12. 13. 28. 24.  1. 11. 20.  0.  5.  2.  3. 23.  4.]


Valores únicos no atributo 'Payment_of_Min_Amount':
['No' nan 'Yes']


Valores únicos no atributo 'Total_EMI_per_month':
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]


Valores únicos no atributo 'Amount_invested_monthly':
[ 80.41529544 118.28022162  81.69952126 ...  24.02847745 251.6725822
 167.16386516]


Valores únicos no atributo 'Payment_Behaviour':
['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'

In [3]:
atributos = [
    'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
    'Credit_History_Age',
    'Payment_of_Min_Amount', 'Total_EMI_per_month', 'Amount_invested_monthly',
    'Payment_Behaviour', 'Monthly_Balance'
]

for atributo in atributos:
    unique_values = df_teste[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")


Valores únicos no atributo 'Changed_Credit_Limit':
[11.27   nan  6.27 ... 17.51 25.16 21.17]


Valores únicos no atributo 'Num_Credit_Inquiries':
[   4.    2.    3. ... 1361.  310.   74.]


Valores únicos no atributo 'Credit_Mix':
[nan 'Good' 'Standard' 'Bad']


Valores únicos no atributo 'Credit_History_Age':
[22. nan 26. 27. 17. 18. 30. 31. 32. 14. 15. 21. 19. 25.  8.  9. 16. 29.
  6.  7. 10. 33. 12. 13. 28. 24.  1. 11. 20.  0.  5.  2.  3. 23.  4.]


Valores únicos no atributo 'Payment_of_Min_Amount':
['No' nan 'Yes']


Valores únicos no atributo 'Total_EMI_per_month':
[4.95749492e+01 1.88162146e+01 2.46992319e+02 ... 1.21120000e+04
 3.51040226e+01 5.86380000e+04]


Valores únicos no atributo 'Amount_invested_monthly':
[ 80.41529544 118.28022162  81.69952126 ...  24.02847745 251.6725822
 167.16386516]


Valores únicos no atributo 'Payment_Behaviour':
['High_spent_Small_value_payments' 'Low_spent_Large_value_payments'
 'Low_spent_Medium_value_payments' 'Low_spent_Small_value_payments'

#### Tratando Payment_Behaviour

In [4]:
df_treinamento['Payment_Behaviour'] = df_treinamento['Payment_Behaviour'].replace('!@9#%8', np.nan)


In [5]:
df_teste['Payment_Behaviour'] = df_teste['Payment_Behaviour'].replace('!@9#%8', np.nan)


In [6]:
# Exibir todos os nomes de colunas (atributos) do DataFrame
print(df_treinamento.columns)


Index(['Unnamed: 0', 'Age', 'Annual_Income', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')


In [7]:

atributos = [
    'Annual_Income',
       'Num_Bank_Accounts', 'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
       'Type_of_Loan', 'Delay_from_due_date', 'Num_of_Delayed_Payment',
       'Changed_Credit_Limit', 'Num_Credit_Inquiries', 'Credit_Mix',
       'Credit_History_Age', 'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance', 
       'Age'
]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")
    

Valores únicos no atributo 'Annual_Income':
[19114.12 34847.84 36455.84 ... 20002.88 39628.99 40312.99]


Valores únicos no atributo 'Num_Bank_Accounts':
[   3    2    1    7    4    0    8    5    6    9   10 1414 1231   67
  572 1488   91  528 1647 1696 1338  649  889 1668  685  857  975 1496
 1534 1620   37 1388 1429 1332 1588  120 1777 1096  803  494  744 1139
  831 1613  741  121  665 1748 1644  823 1356 1651   87  711  450  210
 1671 1722  648  672 1662 1495  510  666  429 1131 1434  980 1026  526
  718 1300 1312 1315  501 1566  480 1042  322  628 1016  333 1265  791
  427  563  905 1190 1036 1611   38  619  555 1769  280  752 1201  812
 1487  222  212 1019 1222  610 1714 1308  525 1158 1115 1616  754 1601
  797 1577  521  703  933  959  809 1089 1656 1113 1715  964 1533 1789
  871  434 1295  565 1724  603  677  541  698 1101  464 1539 1462 1011
 1257 1727   45  244 1266  897  535  484  331  675  826  946 1675  105
 1327  845  549  473  710  527  908   68 1628  371  445 1168  868

### Salvando Dados

In [8]:
df_treinamento.to_csv('../arquivos_csv/treinamento2.csv', index=False)
df_teste.to_csv('../arquivos_csv/teste2.csv', index=False)

