In [2]:
import pandas as pd
import numpy as np

df_treinamento = pd.read_csv('../arquivos_csv/treinamento4.csv', low_memory=False)
df_teste = pd.read_csv('../arquivos_csv/teste4.csv', low_memory=False)


#### Verifica todas as entidades

In [3]:
df_treinamento.columns


Index(['Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour',
       'Credit_Score', 'Auto_Loan', 'Credit-Builder_Loan',
       'Debt_Consolidation_Loan', 'Home_Equity_Loan', 'Mortgage_Loan',
       'Not_Specified', 'Payday_Loan', 'Personal_Loan', 'Student_Loan',
       'dias_atraso', 'divida_restante', 'utiliza_cartao_credito', 'idade',
       'alteracao_limite_credito', 'tempo_credito', 'investimento_mensal',
       'saldo_mensal'],
      dtype='object')

In [4]:
atributos = [
       'Credit_Score' 
       ]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")

Valores únicos no atributo 'Credit_Score':
['Good' 'Standard' 'Poor']




In [5]:
df_teste.columns

Index(['Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour', 'Auto_Loan',
       'Credit-Builder_Loan', 'Debt_Consolidation_Loan', 'Home_Equity_Loan',
       'Mortgage_Loan', 'Not_Specified', 'Payday_Loan', 'Personal_Loan',
       'Student_Loan', 'dias_atraso', 'divida_restante',
       'utiliza_cartao_credito', 'idade', 'alteracao_limite_credito',
       'tempo_credito', 'investimento_mensal', 'saldo_mensal'],
      dtype='object')

#### Faz Uma varredura

In [6]:
atributos = [
       'Credit_Mix', 'Payment_of_Min_Amount', 'Payment_Behaviour', 'Auto_Loan',
       'Credit-Builder_Loan', 'Debt_Consolidation_Loan', 'Home_Equity_Loan',
       'Mortgage_Loan', 'Not_Specified', 'Payday_Loan', 'Personal_Loan',
       'Student_Loan', 'dias_atraso', 'divida_restante',
       'utiliza_cartao_credito', 'idade', 'alteracao_limite_credito',
       'tempo_credito', 'investimento_mensal', 'saldo_mensal'   
       ]

for atributo in atributos:
    unique_values = df_treinamento[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")

Valores únicos no atributo 'Credit_Mix':
[1 2 0]


Valores únicos no atributo 'Payment_of_Min_Amount':
[0. 1.]


Valores únicos no atributo 'Payment_Behaviour':
[0. 1. 2. 3. 4. 5.]


Valores únicos no atributo 'Auto_Loan':
[1 0]


Valores únicos no atributo 'Credit-Builder_Loan':
[1 0]


Valores únicos no atributo 'Debt_Consolidation_Loan':
[0 1]


Valores únicos no atributo 'Home_Equity_Loan':
[1 0]


Valores únicos no atributo 'Mortgage_Loan':
[0 1]


Valores únicos no atributo 'Not_Specified':
[0 1]


Valores únicos no atributo 'Payday_Loan':
[0 1]


Valores únicos no atributo 'Personal_Loan':
[1 0]


Valores únicos no atributo 'Student_Loan':
[0 1]


Valores únicos no atributo 'dias_atraso':
[5. 3. 1. 2. 0. 4.]


Valores únicos no atributo 'divida_restante':
[6. 2. 0. 7. 3. 5. 1. 4.]


Valores únicos no atributo 'utiliza_cartao_credito':
[1. 0. 3. 4. 2.]


Valores únicos no atributo 'idade':
[1. 0. 4. 2. 3. 5.]


Valores únicos no atributo 'alteracao_limite_credito':
[5. 3. 1. 0. 2

In [7]:
atributos = [
       'taxa_juros'
       ]

for atributo in atributos:
    unique_values = df_teste[atributo].unique()
    print(f"Valores únicos no atributo '{atributo}':")
    print(unique_values)
    print("\n")

KeyError: 'taxa_juros'

In [ ]:
# df_treinamento['Type_of_Loan'].isnull().sum()


In [ ]:
df_treinamento.head()

Credit_Mix  Payment_of_Min_Amount  Payment_Behaviour Credit_Score  \
0           1                    0.0                0.0         Good   
1           2                    0.0                1.0         Good   
2           2                    0.0                2.0         Good   
3           2                    0.0                3.0         Good   
4           2                    0.0                4.0         Good   

   Auto_Loan  Credit-Builder_Loan  Debt_Consolidation_Loan  Home_Equity_Loan  \
0          1                    1                        0                 1   
1          1                    1                        0                 1   
2          1                    1                        0                 1   
3          1                    1                        0                 1   
4          1                    1                        0                 1   

   Mortgage_Loan  Not_Specified  ...  utiliza_cartao_credito  idade  \
0              0              0  ...                     1.0    1.0   
1              0              0  ...                     0.0    1.0   
2              0              0  ...                     3.0    0.0   
3              0              0  ...                     0.0    1.0   
4              0              0  ...                     1.0    1.0   

   renda_anual  emprestimos_obtidos  n_pagamentos_atrasados  \
0          0.0                  0.0                     0.0   
1          0.0                  0.0                     0.0   
2          0.0                  0.0                     0.0   
3          0.0                  0.0                     0.0   
4          0.0                  0.0                     0.0   

   alteracao_limite_credito  consultas_credito  tempo_credito  \
0                       5.0                0.0            4.0   
1                       5.0                0.0            3.0   
2                       3.0                0.0            4.0   
3                       3.0                0.0            4.0   
4                       5.0                0.0            4.0   

   investimento_mensal  saldo_mensal  
0                  0.0           0.0  
1                  0.0           4.0  
2                  0.0           0.0  
3                  4.0           4.0  
4                  0.0           0.0  

[5 rows x 29 columns]